require 'jekyll/scholar'
require 'jekyll/scholar/extra_defaults'
require 'jekyll/scholar/extras_utilities'
require 'jekyll/scholar/extras/bibliography_year'
require 'jekyll/scholar/extras/bibliography_bytype'
